# numpy

In [1]:
import numpy as np

### worksheet 5 recap
- create a numpy array from 0 to 10, with step=2
- square every element of the array
- exponentiate every element of the array
- turn every number to a negative and exponentiate

In [2]:
a = np.arange(0,10,2)

In [3]:
a

array([0, 2, 4, 6, 8])

In [4]:
a**2

array([ 0,  4, 16, 36, 64])

In [5]:
np.exp(a)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03])

In [6]:
-a

array([ 0, -2, -4, -6, -8])

In [7]:
np.exp(-a)

array([1.00000000e+00, 1.35335283e-01, 1.83156389e-02, 2.47875218e-03,
       3.35462628e-04])

### python list recap
- now try to create a python list from 0 to 10 with step=2
- square every element of the list
- exponentiate every element of the list

In [8]:
import math

In [9]:
b = list(range(0,10,2))

In [10]:
b

[0, 2, 4, 6, 8]

In [11]:
b**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [12]:
for i in b:
    print(b[i]**2)

0
16
64


IndexError: list index out of range

In [13]:
b

[0, 2, 4, 6, 8]

In [14]:
for i in b:
    print(i**2)

0
4
16
36
64


In [15]:
for i in b:
    print(i)

0
2
4
6
8


In [16]:
b

[0, 2, 4, 6, 8]

In [17]:
b[0]

0

In [18]:
for idx, val in enumerate(b):
    print(f'{idx},{val}')

0,0
1,2
2,4
3,6
4,8


In [19]:
b

[0, 2, 4, 6, 8]

In [20]:
[0, 1, 2, 3, 4]

[0, 1, 2, 3, 4]

In [21]:
b[0], b[1], b[2], b[3], b[4]

(0, 2, 4, 6, 8)

In [22]:
type(b)

list

In [23]:
type(enumerate(b))

enumerate

In [ ]:
for i,j in enumerate(b):
    print(b[i]**2)

In [24]:
for i,j in enumerate(b):
    print(j**2)

0
4
16
36
64


In [25]:
for i in b:
    print(i**2)

0
4
16
36
64


In [27]:
a = [i**2 for i in b]

In [28]:
a

[0, 4, 16, 36, 64]

### sums and divisions
- create two variables with values 2 and 3
- add the two in vanilla python
- do the same with numpy
- divide the two in vanilla python
- do the same with numpy

In [29]:
x = 2
y = 3
x + y

5

In [30]:
np.add(x, y)

np.int64(5)

In [31]:
np.divide(x, y)

np.float64(0.6666666666666666)

In [32]:
x/y

0.6666666666666666

## boolean indexing in numpy
- create an array from 0 to 10 and filter out the numbers less than 4 using boolean indexing


In [33]:
c = np.arange(0,10)

In [34]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
c[~(c < 4)]

array([4, 5, 6, 7, 8, 9])

In [40]:
c > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
c[c > 4]

array([5, 6, 7, 8, 9])

In [42]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
f = np.array([0, 1, 2, 3])

In [44]:
c[f]

array([0, 1, 2, 3])

## assigning constants to slice
- create an np array from 0 to 12
- change the first 6 numbers to 1
- try the same with in python, using python list from 0 to 12

In [49]:
y = np.arange(12)

In [50]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
y[:6] = 1

In [52]:
y

array([ 1,  1,  1,  1,  1,  1,  6,  7,  8,  9, 10, 11])

In [53]:
y = list(range(12))

In [54]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [55]:
y[:6] = 1

TypeError: must assign iterable to extended slice

## basic functions
- write a function to add two numbers and add some basic comments
- run it once on two integers
- now run it once on an integer and a string
- can you handle this error better and return nan if one input is a string? Use a general Exception


In [74]:
def add_numbers(foo, bar):
    """
    a function to add two numbers
    input: foo, integer; bar, integer
    output: integer
    """
    try:
        res = foo + bar
    except Exception as e:
        print(f'exception: {e}')
        #res = np.nan
    return res

In [ ]:
'foo' * 3

In [75]:
res = add_numbers(1,'abc')

exception: unsupported operand type(s) for +: 'int' and 'str'


UnboundLocalError: cannot access local variable 'res' where it is not associated with a value

In [67]:
res = add_numbers(1,2)

In [68]:
res

3

In [62]:
foo

NameError: name 'foo' is not defined

In [69]:
add_numbers(1, 'abc')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [71]:
add_numbers('xyz ', 'abc')

'xyz abc'

# loops
- create a dictionary with 5 students names and their fav colors
- loop over the dictionary and print keys and values
- now choose any two students and only print names and colors for them
- now choose any one student and only print their fav color
- now choose any one student and do not print their fav color. Only print for everyone else
- can you write a while loop that loops over the keys and prints them?

In [89]:
python_class = {
    'alejandro': 'purple',
    'himat': 'green',
    'alexander': 'blue',
    'carmen': 'yellow',
    'elizabeth': 'black'
}

In [90]:
python_class

{'alejandro': 'purple',
 'himat': 'green',
 'alexander': 'blue',
 'carmen': 'yellow',
 'elizabeth': 'black'}

In [91]:
class_keys = list(python_class.keys())

In [92]:
class_keys

['alejandro', 'himat', 'alexander', 'carmen', 'elizabeth']

In [93]:
idx = 0
while idx < len(class_keys):
    print(class_keys[idx], python_class[class_keys[idx]])
    idx = idx + 1

alejandro purple
himat green
alexander blue
carmen yellow
elizabeth black


In [79]:
type(python_class.items())

dict_items

In [80]:
python_class.items()

dict_items([('alejandro', 'purple'), ('himat', 'green'), ('alexander', 'blue'), ('carmen', 'yellow'), ('elizabeth', 'black')])

In [78]:
for k,v in python_class.items():
    print(k,v)

alejandro purple
himat green
alexander blue
carmen yellow
elizabeth black


In [81]:
for k,v in python_class.items():
    if k == 'alejandro' or k == 'himat':
        print(k,v)
    else:
        print('not the chosen student')

alejandro purple
himat green
not the chosen student
not the chosen student
not the chosen student


In [83]:
for k,v in python_class.items():
    if k == 'alejandro':
        print(k,v)
    elif k == 'himat':
        print(k,v)
    else:
        print('not the chosen student')

alejandro purple
himat green
not the chosen student
not the chosen student
not the chosen student


In [84]:
for k,v in python_class.items():
    if k == 'alejandro':
        print(v)

purple


In [85]:
for k,v in python_class.items():
    if k == 'alejandro':
        print(v)
        break

purple


In [86]:
for k,v in python_class.items():
    if k == 'alejandro':
        print('')
    else:
        print(v)


green
blue
yellow
black


In [87]:
for k,v in python_class.items():
    if k != 'alejandro':
        print(v)

green
blue
yellow
black


In [88]:
for k,v in python_class.items():
    if k == 'alejandro':
        continue
    print(v)

green
blue
yellow
black


## review all worksheets and homeworks!